language: c
before_install:
  - cd /tmp && wget http://www.cmake.org/files/v2.8/cmake-2.8.12.1.tar.gz && tar -xvf cmake-2.8.12.1.tar.gz && cd cmake-2.8.12.1
  - ./configure --prefix=/usr && make && sudo make install
  - cd $TRAVIS_BUILD_DIR
compiler:
  - gcc
  - clang
# Change this to your needs
script: ./bin/cmake . && make
notifications:
    email: navaneethkn@gmail.com
